### ISSUE TITLE
Prevent event firing from a cell.

### ISSUE THREAD

**Issue by danielesalvatore** [deitch/jstree-grid#105]
Hello everyone,

First of all thank you for the plugin! Secondly, I would like to add a button on each list's item. I would like to do not fire the jstree selected event if the button is clicked (because i would open a modal instead).

Is it possible to prevent event firing for a certain column? How would you implement my scenario in case?

thank you

**Comment by deitch** [comment]
Hey @danielefenix very glad you enjoy it. It was the offshoot of work I did at a client a bunch of years back. I convinced them it would have better support and benefit to them and the community if we open source it. It must have worked!

So you add a button inside a cell, which is straightforward, but when a cell is clicked, it automatically fires the `select_cell.jstree_grid` event. You want to suppress the event?

If that is it, why would you care about the selected event? Why not just let it fire and not put in a handler?

**Comment by danielefenix** [comment]
@deitch thank you for your reply. 

I describe my scenario.
I am building a page used to query a table and download the selected data. The page is divided in two main sections: the selectors and the result table. The selectors section contains four JsTree. Their content is refreshed on every selection (e.g. imagine that JsTree2 is refreshed if one item of JsTree1 is selected). In order to implement the controller that refreshes the selectors I listen to the JsTree select_node event, I can which JsTree was clicked and perform the refresh accordingly.

One of the JsTree selector should have a button in its items (it will open a modal to explain what the item means), aside the item label. I would like to discriminate the two kind of clicks: if I click on the button i would like to open the modal but not to refresh the other selectors, if i click on any other part of the JsTree item i would like to refresh the other selectors.

If I understood your suggestion, you say to listen to select_cell.jstree_grid event. But the item will be composed by two part: label and button. Both of them would be a cell and so both of them would trigger the select_cell.jstree_grid event. Am I right? Do I have a way to understand which is the column from which the clicked cell come from in order to open the modal only if  the cell of the button was clicked?


Thank you very much for your time and your support,

Bests

**Comment by deitch** [comment]
Oh, I get it (I think). Why not just check where it came from in your `select_cell` event handler?If it came from the button, do nothing? Maybe a jsfiddle would help?
