### ISSUE TITLE
Rows in the second column have the wrong offset.  Maybe AngularJS problem?

### ISSUE THREAD

**Issue by DeegC** [deitch/jstree-grid#109]
Hello,

I'm using jstree+jstreegrid in a very simple AngularJS app.  My problem is that the rows in the second column are displaying on the wrong row.  You can see the problem on this plunker:

http://plnkr.co/edit/96lOMMiwu5UBe9NpJPKT?p=preview

The only non-standard thing I'm doing is using ngJsTree to make it easier to configure jstree from AngularJS.  Project is here: https://github.com/ezraroi/ngJsTree

Can you take a look and tell me what I'm doing wrong or if it's a bug?

Thanks,
DG

**Comment by deitch** [comment]
Hmm, the `ul` containing the jstree in the left column appears to have a `top-margin: 16px;` 

I am not sure where it is coming from, we will need to figure it out.

I have to admit, the alignment for jstreegrid has been a huge pain. The original version extended the `li` for each row in the tree. That was great for vertical alignment, but getting headers and horizontal alignment proved to be a nightmare. So we shifted to the `table` model. The horizontal alignment works perfectly, but now vertical alignment is difficult.

**Comment by deitch** [comment]
This is driving me bonkers. I cannot find where the 16px margin is applied.

**Comment by akostajti** [comment]
Is it somehow possible to switch back to the original behaviour (so using the span elements wrapped into the li elements). I have the same problem. With an earlier version we already had a fix for vertical alignment but now we cannot find a solution for the horizontal alignment.
Which is the branch or the most recent tag that I could use with jstree 3 and has the old behaviour?

**Comment by deitch** [comment]
@akostajti unfortunately, none. We switched to the tabular layout back in May 2014 with commit f56aa288e563ebed5fe1114357e5f2159931b3ec. So much has changed since then (159 commits and counting) - it was impossible to maintain both - that a switch back will break many other things.

The reality is that either vertical alignment is brutal or horizontal alignment is brutal.

The *really* correct solution is to have this a core part of the tree, and make the entire tree a table. Opening/closing nodes just adds/removes rows from the table. But that only matters for the grid; for everything else, it works fine with `li`. So jstree is unlikely to go down that path.

Not a satisfying answer, I know.

**Comment by deitch** [comment]
Oops, hit "Comment" before I was done.

I have no doubt that if we spent enough hours on it, we eventually would get it. But there is the day job....
