### ISSUE TITLE
Breaks if node id contains slashes or spaces

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#123]
There are several jQuery selector errors when node ids contain forward slashes or space characters.

**Comment by deitch** [comment]
jsfiddle, please?

**Comment by adamjimenez** [comment]
http://jsfiddle.net/adamjimenez/1nooy3vv/

**Comment by deitch** [comment]
Right. Well, I added some additional support, but it still won't work. jQuery (really Sizzle) will not be able to find nodes using those illegal characters.

The net of it is that it isn't worth the effort to try and figure out how to get around the limitation. Space and slash characters are not legitimate in node IDs. See here http://www.w3.org/TR/html401/types.html#type-name

The issue was raised earlier, we added what support we could, but the short of it is: don't do it.

**Comment by adamjimenez** [comment]
It's natural to use a file path as a node id and jsTree doesn't have any issues with this.
In fact they even use slashes and spaces in their official demos:
https://www.jstree.com/demo/

JSON:
https://www.jstree.com/demo_filebrowser/index.php?operation=get_node&id=App+Server%2FKPI+Criteria

```
[{"text":"Applications","children":true,"id":"App Server\/KPI Criteria\/Applications","icon":"folder"}...]
```

**Comment by deitch** [comment]
It may feel natural, but the W3C spec is quite clear. For a while jstree didn't support it. Ivan only put in support after it was less effort to just do a string replace and escape the ID than to keep explaining to people why it is illegitimate.

The principled person in me says, "no way." The practical says, "sure, we did it before." The problem is that we need to be able to search for nodes, and `jQuery.find()` simply does not support it.

Using your example, `"root 1/a very long node" ` is escaped out to `"root\ 1\/a\ very\ long\ node"`. That actually does work (even thought it shouldn't, and all of the browsers should ignore it but don't, and to be fair, one day Chrome or FF will start respecting the spec and this simply will not work). But trying to do `someNode.find("div#root\ 1\/a\ very\ long\ node")` returns an empty list. Sizzle simply cannot match it. 

The problems primarily are https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L480 and https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L726 and the following few rows.

If you can find a workaround, happy to implement.

**Comment by adamjimenez** [comment]
Why didn't jsTree use a data attribute instead?
I will look into a workaround.

**Comment by deitch** [comment]
Ho! data attribute is an interesting idea. I wonder if Sizzle/jQuery would find it that way. Mind you, it can get inefficient if we have to search lots of nodes, but no worse than classes.

**Comment by deitch** [comment]
Data attribute works *really* nicely, even with illegal names. I still don't like it, and one day a browser will respect the spec and not support it, and nothing we do will help, but for now...

**Comment by adamjimenez** [comment]
I can't find anything in the spec that says we can't use slashes or spaces in data attribute values..

**Comment by deitch** [comment]
No, you misunderstood me. I meant, it still is in the ID, even if we also add it to the data attributes.

Using it in data attributes makes it work perfectly without escaping, and allows perfect searching. Works really well. v3.3.1, just pushed out to github and npm.

**Comment by adamjimenez** [comment]
nice!

I think there are still some issues around: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L254

**Comment by deitch** [comment]
> Nice!

Back at you. I hadn't thought of using data attributes. You did, and it works really nicely.

> I think there are still some issues

Can you be specific? I agree the `find()` should be more intelligent, but how does the issue manifest itself?

**Comment by adamjimenez** [comment]
Error when hovering over child node with illegal chars.

Uncaught Error: Syntax error, unrecognized expression: .jsgrid_really long/ named child_col
https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L259

**Comment by deitch** [comment]
It is more than that. We need fixes throughout here:

* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L215
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L251
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L254
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L259
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L263
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L268
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L274
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L288
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L329

Of course, the ID itself is escaped, so we will need to keep the unescaped ID somewhere...

**Comment by deitch** [comment]
All of those now are fixed.

**Comment by adamjimenez** [comment]
Great stuff, thank you.

On 21 November 2015 at 20:19, Avi Deitcher <notifications@github.com> wrote:

> All of those now are fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deitch/jstree-grid/issues/123#issuecomment-158678659>.
>



-- 
Best regards,
Adam Jimenez
