### ISSUE TITLE
Resizing is erratic when all columns are assigned a width

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#126]
see:
http://jsfiddle.net/adamjimenez/0qzo25qu/

**Comment by deitch** [comment]
Look at the file I just added to the repo called `tests/fixed-widths-resize-test.html`.

If you load it, all 3 columns are given equal width, 1/3 of the entire viewport width, rather than the fixed `110px` assigned. If only 2 columns have widths, the remaining one is given `auto` and it all works out. But when all three are given fixed widths, it seems to treat them as proportions, rather than fixed widths.

The reason for that, in turn, is because of this line https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L174

It sets `'.jstree-grid-table {table-layout: fixed; width: 100%;}`

Since the table is set to `100%`, and the `div` it is in is not provided with any width, it takes up the whole thing and treats the sizes as proportions in some browsers, adds blankspace in others, etc. In other words, unpredictable. 

When you start to resize, all of the calculations are thrown off. I think this is by the browser trying simultaneously to respect the changing fixed sizes we give each column and the 100% table width.

You can easily do it without jstreegrid:

1. Load the above file
2. In the console, `$("col:eq(1)").width()` - this will give you the actual width. In my use case right now it is 463px
3. In the console, `$("col:eq(1)").width(462)` - this should shrink that one column by 1px... and watch everything else jump.

I am not sure how to get around this browser issue. Any thoughts?

**Comment by adamjimenez** [comment]
A couple of ideas. Either switch to divs so that we have greater control over the widths or add an empty auto width column to the right which will fill the remaining space.

**Comment by deitch** [comment]
Switch to `div`s? But it is a table!

The table is `width: 100%`, so it fills the wrapping `div`, but we do control that `div`. Something we can do there perhaps?

**Comment by deitch** [comment]
This is fixed as of the latest release 3.4.0+

**Comment by adamjimenez** [comment]
Good old divs. The new update is working a lot better for me, really good job. I've submitted a few minor fixes. Thanks for attending to these issues.

**Comment by deitch** [comment]
You kidding? **Thank you.** Your pull requests have been filling my inbox in a good way.

This was a side effect of a project I did for a client a few years back. I saw their problem, realized it was better abstracted out, then got them to open source it. I have been putting a *lot* of time into it over the years, all for the good of the community. Would love to find a way to build something around it, but never could.

Whenever I can, if I abstract things out, I try to get clients to allow me to open-source them. They then languish for months or even years, then suddenly get picked up. 

I might have asked but... what are you using it for?

**Comment by adamjimenez** [comment]
I'm using it for the [new ShiftEdit](https://shiftedit.net/blog/jquery-ui-build).

**Comment by deitch** [comment]
That is pretty cool. Is the idea to allow me to develop anywhere in a browser, liberate me from my laptop? I store everything in the cloud (dropbox, github, etc.), and have my own IDE-driven workspace?

I assume you are using https://ace.c9.io embedded?

**Comment by adamjimenez** [comment]
Yes, that's the idea and it does use Ace.

**Comment by deitch** [comment]
I have started using Ace embedded in Codiad in a recent project. Client was editing configurations on individual servers. Centralize, bring a Web interface via Ace... beautiful.

**Comment by deitch** [comment]
And I should look at shiftedit. I like the idea.

What happens when you are offline (train, airplane, etc.)?

**Comment by adamjimenez** [comment]
ShiftEdit can be used for [working locally](https://shiftedit.net/blog/working-locally) via a proxy.

**Comment by deitch** [comment]
So you just run it as a local PHP server on your laptop?

As I watch the debate of html5 vs native apps on mobile - one that is till evolving - on the desktop Web has won out for just about everything on the Web. But for local access, we still use native apps.

You are trying to say, "we can use Web for that too."

I think an interesting approach would be if the OS natively supported these kinds of Web apps.

**Comment by adamjimenez** [comment]
Yes by using xampp or equivalent, it's a little clunky to set up but it works.
I think the only way to get real [file system access](https://developer.chrome.com/apps/fileSystem) is via an installable chrome app.
