### ISSUE TITLE
Data object is lost when dnd is enabled in jstree

### ISSUE THREAD

**Issue by jacobbunkley** [deitch/jstree-grid#142]
https://jsfiddle.net/jacobbunkley/v7y1dd5m/7/

Expected behavior: The data object, which contains the additional columns, should be preserved when moving a node from one tree to another.

Seen behavior: The data object is either lost, or rebuild as an empty object (can be seen by using the BASB (json of tree will print out). It doesn't look like the data object can be recovered at this point.

**Comment by deitch** [comment]
When you drag and drop, the data object appears to be wiped or rewritten. Not clear to me if this is because we are inspecting the wrong object, or if something fundamental is happening with dnd in jstree.

@vakata can you shed some light on this? Why does doing a drag and drop cause the `get_json()` to return an empty array?

**Comment by jacobbunkley** [comment]
Any update??

**Comment by deitch** [comment]
Not a clue. We need to hear from @vakata as to why this behaviour works this way.

**Comment by vakata** [comment]
When copying a node (which is what happens when you move between trees - the node is first copied and then deleted from the original tree) jsTree will create a copy of the node, but without any ID, data or state. If you need some of this information it can be restored in the copy_node.jstree event handler - you can a reference to the old object and the new object, so you can copy the data (and/or ID) as well. The same goes for nested nodes - you will have to iterate the nodes and copy. 

There is a good reason to clear this data and I am reluctant to allow copying without clearing. Unfortunately this means that in more advanced use cases you have to copy there properties manually. There is a post in the groups page (I believe 5-8 lines) which handles exactly that.

Best regards,
Ivan

**Comment by deitch** [comment]
> There is a post in the groups page (I believe 5-8 lines) which handles exactly that.

The Google Group discussion? Perfect, happy to put it in. There are ~40k topics though. Can you give us a bit of a pointer?

**Comment by deitch** [comment]
Hold on. Do you mean this? 

https://groups.google.com/forum/#!searchin/jstree/copy$20data/jstree/ZtC33iEwNbM/F9HdkrUAdAYJ

**Comment by deitch** [comment]
Or perhaps this:

https://groups.google.com/forum/#!searchin/jstree/copy$20data/jstree/_NvazSz1jJs/BY9NELE1KVQJ

Or:

https://groups.google.com/forum/#!searchin/jstree/copy$20data/jstree/Hv34almrMy4/vip422ApmlMJ

Which is the best?

**Comment by vakata** [comment]
This one handles the node itself:
https://groups.google.com/forum/#!searchin/jstree/copy$20data/jstree/_NvazSz1jJs/BY9NELE1KVQJ

This one handles nested children:
https://groups.google.com/forum/#!searchin/jstree/copy$20data/jstree/Hv34almrMy4/vip422ApmlMJ

Combine them to make sure all data is copied from source to target.
Let me know if I can help.

**Comment by deitch** [comment]
@vakata that was helpful. I managed (rather easily) to get the `.on(copy_node.jstree)` event working and copying the data.

Where I got stuck was the following. The dragged (and therefore copied) node gets called to `redraw_node` *before* the `copy_node` event. So it redraws without the data copied.

**Comment by jacobbunkley** [comment]
Thanks guys for the info! @deitch do you have a jsFiddle showing your example??

**Comment by vakata** [comment]
@deitch oh, sorry about that. 

The thing is that I am not sure how to fix this - if the event is triggered before the redraw then manipulating or reading the DOM won't be an option, on the other hand - if triggered after - anything you set to the data attribute to modify the redraw will not be applied. I tried to suit the first case as it happens more often. 

The dirty solution would be to call redraw again manually which can be heavy on large trees. I will see what I can do and let you know, but any major changes will be left for v4 which I will try to push out by the end of this year (so quite a long way to go).

**Comment by deitch** [comment]
Oops. Catch-22. :-)

So we could call redraw again, but it can get heavy. I will go for that for now.

Is there any way to know what the data would be from the redraw? Or not really?

**Comment by deitch** [comment]
For now, I am patching it with calling `_prepare_grid` again. No need to redraw the whole node, but yes the grid. On very large trees there will be a performance hit. We will need to think how to handle it in v4.

**Comment by jacobbunkley** [comment]
Hey @deitch the fix works for single nodes moving... it does not work for multiple nested nodes moving trees...

**Comment by deitch** [comment]
Drat. OK, reopen this and modify the fiddle to show the issue?

**Comment by jacobbunkley** [comment]
OK here you go...
https://jsfiddle.net/v7y1dd5m/8/

**Comment by deitch** [comment]
@jacobbunkley so I don't get it. What do you mean by "doesn't work for multiple nested nodes"? The fiddle looks the same. What is the erroneous behaviour?

**Comment by jacobbunkley** [comment]
Sorry for the lack of information on the last message...
https://jsfiddle.net/v7y1dd5m/10/

When you move Row 3 to be a child of Row 1, but above Row 2, then strange things start happening, like:
1. Row 3 is pasted but it is not removed from the old tree... 
2. The grid values are saved, but do not show on the tree (it's like the redraw never occurred for the columns)
3. The mouse cursor still shows like you are holding down in the mouse. In fact, if you click again and again, you will have multiples of the same row over and over again.

**Comment by deitch** [comment]
Oh, OK, now I get it. Thus begins the long haul of figuring out why.

**Comment by deitch** [comment]
> 2. The grid values are saved, but do not show on the tree (it's like the redraw never occurred for the columns)

What does that mean, that they are saved?

**Comment by deitch** [comment]
And I have to ask, what does "BASB" stand for? I know what it does, but what does it stand for?

**Comment by deitch** [comment]
I just updated the fiddle by adding `js3` and `js4` that are identical to `js1` and `js2` but without the grid plugin, so we can compare what happens when there is a grid vs no grid.

**Comment by jacobbunkley** [comment]
When I say saved, I mean that when I drag and drop a selection, the name column shows correctly in the tree. It also shows when I click the BASB. The grid columns do not show correctly in the tree, however they are present when I click the BASB.

BASB stands for BIG ASS SAVE BUTTON... ode to one of my old college professors...

**Comment by deitch** [comment]
> BASB stands for BIG ASS SAVE BUTTON... ode to one of my old college professors...

LOL! You just made my day!

**Comment by deitch** [comment]
OK, 1 & 3 are solved. 2 is half done. Need to add a second "BASB".

**Comment by deitch** [comment]
@vakata I need your help here.

Here is the relevant code:

````javascript
			.on("copy_node.jstree", function (e, data) {
				var tree = data.instance, obj = tree.get_node(data.node,true);
				copyData(tree,data.original,data.node,true);
				tree._prepare_grid(obj);
				return true;
			})
````

The important line is the one that says `copyData()`. It basically takes the original node and the copied node, and copies the data. Works great.

If the original node has children, then it recurses through `node.children_d`, takes the data off of each of those and adds it to the children of the target node. `node.children_d` is an array of string IDs, so I just do `tree.get_node(id)` to get the `node` object, which gives me the `node.data` to extract data from the original node and append to the target.

The problem arises if I drag and drop from one tree to another. The `copy_node` event itself occurs on only one tree (the target), so I can do `tree.get_node(id)` for a child and get the node object.

But I cannot do `tree.get_node(id)` to get the data from the source, because the `tree` is the wrong one! 

Is there any way to get the actual `tree` object from a node itself, so I can do `tree.get_node(id)` for the right `tree`? Does a `node` object hold a reference to a tree?

Essentially, I really want to walk from a `node` object to its children `node` *objects*, but `children` and `children_d` hold arrays of String IDs.

**Comment by vakata** [comment]
My guess is you are looking for `old_instance`:
https://www.jstree.com/api/#/?q=copy_node.js&f=copy_node.jstree

**Comment by deitch** [comment]
@vakata is the man! Thanks, Ivan.

@jacobbunkley I am pushing out the commit with it fixed, and publishing to npm.

**Comment by deitch** [comment]
And published. 3.5.13.
