### ISSUE TITLE
Selection state gets messed up when selecting nodes via API

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#143]
See http://fiddle.jshell.net/5eLsvxds/
Run the test and select the bottom node ("Level 1").
The event listener deselects all nodes and selects the first one instead. But the grid cells of the bottom node stay "selected".
I wonder if that's because the plugin uses event to bind its methods instead of just wrapping the existing functions like in https://github.com/vakata/jstree/blob/master/src/sample.js.

**Comment by deitch** [comment]
I suspect it is. The interesting question is why using the API to `tree.deselect_all` or `tree.select_node` does not cause the event to trigger.

@vakata looks like we need your help again.

jstreegrid listens for `"select_node.jstree"`, `"deselect_node.jstree"`, "deselect_all.jstree"` events. It appears that if you use the API to explicitly `tree.deselect_all` or `tree.select_node`, the event is not called?

**Comment by jochenberger** [comment]
If you set breakpoints in the select and deselect_all handlers in jstreegrid, you can see that at first, the deselect_all handler runs, then the select handler is called twice, once for j1_1 and once for j1_2 (yes, in that order). After the first run, the highlighting is correct but after the second run. That makes sense because I bind my listeners after the grid plugin does. I wonder if and how this could be fixed. I tried to rewrite some of the code to wrap the selection methods like in the sample but didn't get far.

**Comment by deitch** [comment]
I always am wary of breakpoints in event handlers. There is no guarantee of the order in which it will be caught. As crude as it is, with async event handlers I tend to use log statements.

**Comment by deitch** [comment]
So a little more context. Here is the result of log events if I just click the lower-left cell labeled "Level1" with the ID "j1_2". In each line, `tree:` means it is an event trapped by jstreegrid's event handlers, `html:` means it is in the `selectionChanged` handler in the html sample you gave:

````
tree: deselected all
html: selectionChanged j1_2
tree: deselected all
html: selectionChanged j1_1
tree: selected j1_1
tree: selected j1_2
````

FYI, here is what happens without your added handler:

````
tree: deselected all
tree: selected j1_2
````

Analysis:

1. The first and last lines (1 & 6) - deselect all and select j1_2 - are the result of jstree itself catching the click. It first deselects everything else, then selects that one node `j1_2`.
2. After the deselect all but before making the new selection, your `selectionChanged` event handler is called. Line 2.
3. The `selectionChanged` handler in turn calls deselect_all again, which triggers the handler in jstreegrid. Line 3
4. The `selectionChanged` handler is called again, because you selected `j1_1` in that handler. Line 4.
5. The jstreegrid handler handles the select event for `j1_1`, called because `selectionChanged` selected `j1_1`. Line 5
6. The jstreegrid handler handles the select event for `j1_2`, called by jstree because you originally clicked on it.

I suspect we have a conflict of events going on here, but not sure. I tried stopping the event propagation, but it had no effect.

The jstree deselection happens before your handler, selection happens afterwards.

I suspect there may be no way to use the selection API inside a handler for a selection event?

**Comment by jochenberger** [comment]
Yes, that's pretty much what's happening. I can call `event.stopImmediatePropagation()` inside my handler. If I call it from within the if block, everything seems to work correctly. If I call always call it in the handler, it breaks the grid cell selection because the jstreegrld select handler is not called. That's why I think that the plugin should not rely on events being propagated, but I may be wrong on that one.

**Comment by deitch** [comment]
How else would it catch it? 

More fundamental question: why would you put an event handler on `select` event which in turn does an API `select`?

**Comment by jochenberger** [comment]
> How else would it catch it?

I don't understand what you mean.

> More fundamental question: why would you put an event handler on select event which in turn does an API select?

The example is stripped down of course, my actual use case is more complicated. I want to integrate with React and keep the selection state outside of the tree component's code. And when the selection state changes outside of the component, I need to pass it down to the tree again. That can lead to cases where a handler on the tree updates the state, a new state is computed and passed back down into the component.

**Comment by deitch** [comment]
I am somewhat confused by that. Do you mean that the initial change is *not* caused by the click on the lower-left?

**Comment by jochenberger** [comment]
Yes it is. I just want to catch the select event, compute a new set of nodes that are to be selected and select those.

**Comment by deitch** [comment]
So if we separate this into two steps:

1. User clicks
2. Tree reacts (by highlighting, changing css, etc.)

You want instead to capture 1 and prevent 2 from happening, instead causing your own:

1. User clicks
2. Stop tree from reacting, do my own reactions (like selecting other nodes, etc.)

What happens when you just do this on a regular tree (no grid)?

**Comment by jochenberger** [comment]
See for yourself: fiddle.jshell.net/5eLsvxds/1/
If I remove the grid plugin, the tree does what I want. This is because the tree answers to the click event (which I leave alone). The click handler is the one that calls the `select_node` function. That one in turn fires the `select_node` event. 
That's why I think that the grid should hook into the `select_node` (and other) functions instead of observing the events. IMHO, the events are just for the user to deal with, not for plugins. They should work regardless of what the user does with the events. I *assume* that's how @vakata meant it to work, too.

**Comment by jochenberger** [comment]
Another observation: http://fiddle.jshell.net/5eLsvxds/2/
If I fire the `select_node` event after the tree is loaded, the jstree itself doesn't care, only the grid plugin does. That also leads me to the assumption that the plugins should not react to the events. 
I've checked @vakata's plugins for that but at least the checkbox plugin binds to events too: https://github.com/vakata/jstree/blob/master/src/jstree.checkbox.js#L178. But if I do the same test with the checkbox plugin, things get even stranger: http://fiddle.jshell.net/5eLsvxds/3/. Why does it select `j1_2`? Now I'm confused too.

**Comment by vakata** [comment]
I haven't had the chance to read the whole thread yet, but I thought I'd chime in - only jstree itself and plugins should trigger events. If you trigger events from code that is external to jsTree you may get some very strange results, as you have no way of maintaining the internal state. 

Events indicate that something HAS already happened and the internal state has already updated to match that. If you simply trigger an event - nothing has happened - you are just fooling other parts of the code that something has happened, but the internal state does not represent that.

jsTree plugins listen for *.jstree events as well, but the sender needs to be jstree itself.

Best regards,
Ivan

**Comment by deitch** [comment]
> Now I'm confused too.

LOL! Welcome to my club! :-)

I think the checkbox plugin was a key one I used when first building jstreegrid, with help from @vakata . 

I see a few approaches here:

1. Hook into `select_node` method instead of events. I don't like hooking too deeply (although already do it with `redraw_node`, but even that was reluctant).
2. In your code, instead of listening for the `select` event, hook in at the higher level, i.e. the DOM (ok, jQuery) `click` event, preventing it from becoming a `select_node` until you actually use the API.
3. Have a `post_select.jstree` event. The current one seems to come in earlier.
4. Enable a `select_node.jstree` handler to prevent further event processing by returning false or calling `stopPropagation` or similar.

Part of me likes the 2nd, since what you are trying to do is *prevent* selection, so don't let it ever make it to the tree.

**Comment by deitch** [comment]
Crossed wires! Hey @vakata welcome to the fun.

The question isn't about triggering events. It is about handling triggered events.

It is about the behaviour that happens when an event handler for `select_node` in itself uses the API to deselect or select other nodes. Because the handler gets called in the process, strange things happen.

**Comment by vakata** [comment]
As for the demo (the one that is confisuing) - when triggering a select_node call, you will also select the children of the selected node, because that how three state checkboxes work.

Now to the question - maybe the confusion comes from this - the `select_node.jstree` event is more of an internal one - you should be careful what you do with it. The proper way to listen for changes is the `changed.jstree` event.

**Here is the demo from above, simply using the changed event** (I believe it does what it should):
http://fiddle.jshell.net/5eLsvxds/4/

As for writing plugins - it depends on what the plugin does - sometimes it makes sense to overwrite functions, if you add UI elements it makes sense to listen for user events on those elements, and if you are somehow dependent on the tree state - it makes sense to listen for jstree events and react to those.

**Comment by deitch** [comment]
So `select_node.jstree` is the internal event for jstree itself and plugins to use to modify internal state of the tree or components. `changed.jstree` is the external event for outside consumers. Is that right?

@jochenberger it looks like his change solved everything. Can you confirm and we can close this out?

Thanks @vakata

**Comment by jochenberger** [comment]
Yes, absolutely, thanks both @vakata and @deitch . :-) I'll try to rewrite my component to work with the `changed.jstree` event then.

**Comment by vakata** [comment]
@deitch yes, I encourage all outside consumers to use `changed.jstree`, but as a plugin writer you may of course need to use the `select_node.jstree` - no harm in using it (as you know :)).
But if possible - `changed.jstree` should be used.

The actual difference is that when `select_node` fires the internal state may not yet be applied. For example the checkbox plugin reacts to that event and will in turn select more nodes, but when `changed.jstree` finally fires the internal state should all be sorted out.

**Comment by sfdctower** [comment]
@jochenberger  @deitch  I use both jstree and jstreegrid.  I found this topic because my deselect_all function stopped working.  In my case I had to set `tie_selection `to `true ` within jstree's config to restore functionality to the deselect_all function.

**Comment by AboObe** [comment]
I have a jstree  and the node maybe could be in many lines ,so when I select the node, it selected just the first line ,but I need when  I select the node to select the whole lines not just the first line

**Comment by ViktorReib** [comment]
> I have a jstree and the node maybe could be in many lines ,so when I select the node, it selected just the first line ,but I need when I select the node to select the whole lines not just the first line

Please open a new ticket with an example.

**Comment by AboObe** [comment]
![screenshot from 2019-02-27 09-44-56](https://user-images.githubusercontent.com/38585278/53473934-73819400-3a74-11e9-9817-95eb999b7622.png)

**Comment by AboObe** [comment]
just the first line change background color
i want change background color three line
