### ISSUE TITLE
Search among all the data fields.

### ISSUE THREAD

**Issue by robalvsan** [deitch/jstree-grid#146]
Currently it appears that the 'search' option only searches among the first column elements...could it be possible to expand the searches among the other data columns?

**Comment by deitch** [comment]
I assume you are using just the search plugin? The search plugin does have a `search.jstree` event, but that only responds after the search is done. 

There are 2 modes of search:

1. Show all nodes, but highlight those that match.
2. Show only those that match.

The first might be easier, as we would be able to catch the event after search is done and add the `jstree-search` class to grid cells that match. Still work to be done, but probably doable.

The second is a challenge. What do you do if someone's search matches the second row second cell but not the first cell (tree node)? The default search will hide that. We would need to inject ourselves into the search method itself.

Still, it probably is doable, but unless you have a PR you can offer, it is going to take a while till I can find time to get to trying it.

**Comment by robalvsan** [comment]
Maybe the best option would be give the possibility of choosing the column where to perform the query.

**Comment by deitch** [comment]
Same basic problem, though.

**Comment by kikan** [comment]
I'm also trying to search on all columns. The server parts finds the result, but jsTree seems to be able to display only nodes whose content is matching the search. And the jsTree part is only in the first column (same as you).

I managed to search in all cols adding this to the jstree config :
```coffeescript
    search:
      ajax:
        url: '/lignes_annuaire.json'
      search_callback: (str, node) ->
        regexp = new RegExp(str, "i")
        return node.text.match(regexp) or node.data.personne_text.match(regexp) or node.data.telephone.match(regexp)
```

Only the info of the first col is highlighted though, but the good lines are opened.

**Comment by deitch** [comment]
@kikan that is an interesting idea. You know, I do have access to the search algorithm as it runs through. We could do something sort of like that.

**Comment by deitch** [comment]
Take a look at the latest commit 3.5.19. It will return nodes wherein the tree node itself matches *or* the displayed content of the data matches.

It only does it if you don't do an override like @kikan did above. After all, if you override, you don't want our search algorithm anyways.

**Comment by QueroBartK** [comment]
I'm wondering, are there currently any plans to allow column specific searches? this would result in an input field just below each header (for each column that is specified as searchable; maybe also at the bottom?) and maybe some optional parameters to override the search for specific columns or to override the default text input field to (for example) a combobox or something. (when used with sorting these search rows should stay in place!). This could potentially be used in combination with the current search method which searches over the entire grid.

**Comment by deitch** [comment]
@QueroBartK what would the API look like? I am less concerned with the UI; we can start without one, letting people do their own however they want, as long as the API works, and then add an optional UI component later. But what would the API look like?

The jstree search API is pretty straightforward:

````javascript
tree.search(someString);
````

We override it to enable finding cells. Now we would need to be able to say, "look only in specific columns". 

Also, are we sure this makes sense in the context of the jstreegrid, as opposed to the underlying data? Or is the assumption that, like with current search, it would indicate them by filter and/or highlighting?

**Comment by QueroBartK** [comment]
@deitch hmm, I don't seem to be able to think of a good solution concerning the API, maybe I'll think of one later. The problem is indeed that we'd need to be able to distinguish between a search as it is now and a search on a column (and know which column)

I was indeed thinking that it would work sort of like the current search, thus it would filter and/or highlight.

**Comment by QueroBartK** [comment]
@deitch I've been thinking concerning the API. You could do something like the following:
`
tree.searchColumn(someString, AColumnNumber);
`
This function would do the following things:
1) save the current callback method in a variable
2) set a new callback method that checks only that column (maybe even a callback method set by the user in the options for that column?)
3) call the jstree search function
4) restore the first callback method as callback method

(maybe there are some more steps that need to happen but I think that is the general flow)

concerning the UI it would be nice to have an option to add input fields in the headers or an option to put them at the bottom (or both)

**Comment by deitch** [comment]
So define a new function `tree.searchColumn()`? That could work.

We could just use `tree.search(arg)` and pass arg as an object `{term: "abc", columns: [1,2,3]}`. But there is always a real risk that it will break something else, either now or in the future. So that probably isn't a great idea.

We also could add additional arguments, but (a) again, what if the core `jstree.search()` uses multiple arguments in the future, and (b) `search()` doesn't pass anything other than the first arg to `search_callback()`. So this is not a very good idea either.

In jstreegrid.js LL294-313, we already search among the columns for matches. The native jstree search algorithm calls `search_callback()` for each node in the tree. We augment it by first searching the basic tree nodes, just like the original algorithm (use the exact same search call), and then searching in the nodes.

The problem is that it would get messy in that we would need to handle all of the opening and highlighting. With searching in the tree and *also* in the grid, we just use the existing callback interface provided for `search_callback()`. If we return `true`, it says, "this node matched"; `false` says "it did not". But then jstree itself handles all of the node opening, highlighting, etc.

We would need to replicate all of that, and maintain it. Not something we want to take on.

The real trick here is to use `jstree.search()` but somehow indicate that it *only* should search in certain columns. We already override the search algorithm, so if there is some way to indicate it, that would be the best (and only maintainable) solution as far as I can see.

Maybe one of the above proposed options isn't so bad?

**Comment by QueroBartK** [comment]
I did indeed use a new function to avoid conflict with changes that might be made in the future to `jstree.search()`

I've quickly created a function that does work in jstreegrid. You can see it [here](https://gist.github.com/QueroBartK/6a0e7da452cb70d37d05ec31a84fc0c9)

It does use some internal status of jstreegrid so if you'd want to test it you'd need to add it in your js file somewhere.

There are probably better solutions but this seems to do the job. It does miss some things. Like the ability for the others to use their own search method as callback but I think it is a good starting point. Anyway, you're free to do whatever you want with this :)

**Comment by deitch** [comment]
How does this work? It appears to save any old `search_callback()`, set a new one, search the column, and then restore `search_callback()`. Is that right? 

I like how it uses the existing `search()` function, so we don't need to redo all of the highlighting and displaying work.

All in all, it actually seems like a reasonable solution. I am good with implementing it.

> It does use some internal status of jstreegrid so if you'd want to test it you'd need to add it in your js file somewhere.

What do you mean? Which internal part?

**Comment by QueroBartK** [comment]
> How does this work? It appears to save any old search_callback(), set a new one, search the column, and then restore search_callback(). Is that right?
 
that is correct!

> I like how it uses the existing search() function, so we don't need to redo all of the highlighting and displaying work.
> 
> All in all, it actually seems like a reasonable solution. I am good with implementing it.

I did find some drawbacks to this currently as I've been testing this myself. One of the drawbacks is that it currently doesn't consider existing filters on other columns (or even have the option to consider these). I'm currently testing something out, once this is a bit more refined I'll share it with you.

> > It does use some internal status of jstreegrid so if you'd want to test it you'd need to add it in your js file somewhere.
> 
> What do you mean? Which internal part?

I don't think I can call `getCellData` from a function outside of the jstree-grid scope and the way I call the settings might also only work from within this scope. (which is what I meant with that.)

**Comment by deitch** [comment]
Let's move the conversation to your V2 in #180
