### ISSUE TITLE
Rows are narrower than the jstree (in Firefox)

### ISSUE THREAD

**Issue by srkunze** [deitch/jstree-grid#166]
The rows of the grid are displayed too narrow. So, the complete grid gets out of sync with the tree.

**Comment by deitch** [comment]
I don't understand. Is this an issue, or is it not?

**Comment by srkunze** [comment]
Sorry, a colleague of mine told me that in Firefox it does not work for him as I usually develop in Chrome.

However, somebody else does not had the same issue in Firefox so I suspect this is a misconfiguration on my colleague's Firefox.

**Comment by deitch** [comment]
No worries. Unfortunately, because of how it has to leverage the existing tree, it always will be either sensitive due to css to slight changes either in columns (the old way) or rows (since ~3.0.0). 

I have wanted to do an overhaul of jstree-grid for a long time, perhaps make it an Aurelia/Polymer/Angular/Angular2 component, remove some dependencies. But that is at least several intensive days of work, so until someone wants it enough to hire me to consult for it, it probably won't happen.

May I ask, how are you using it?
