### ISSUE TITLE
jstreegrid currently pastes poorly into popular applications like google sheets / excel.  I will look into a fix

### ISSUE THREAD

**Issue by sfdctower** [deitch/jstree-grid#248]
Hi Avi @deitch 

When I copy jstreegrid data to clipboard via mouse selection drag + copy it pastes poorly into popular applications like google sheets / excel.

The data pastes into 1 column with multiple rows
whereas I had hoped it would have pasted into multiple columns and multiple rows (per jstreegrid's definition) 

My selection + copy was made from multiple jstreegrid columns and multiple jstreegrid rows, so why does it paste into 1 column in apps like Excel?   Any idea how to fix this?  I will do some further research.

Thank you,

**Comment by deitch** [comment]
How exactly did you copy? Maybe a screencast video to show it? What platform are you doing this on, Windows/Mac/Linux?

I am not completely sure how copy-paste works for things like that, so it will be an interesting debugging.

**Comment by deitch** [comment]
Normal web tables do copy normally. Try from [this page](https://www.w3schools.com/css/css_table.asp) and it works. Do you know how it transmits that it is a table per se?

**Comment by deitch** [comment]
I strongly suspect it is because we use `<div>` elements for various rows and columns, and not a `<table>`.

**Comment by peternoges** [comment]
i couldn't figure it out.. I tried adding various CSS rules such as the ones below but did not work.

```
div.jstree-grid-header{
  display:table-row;
}
div.jstree-grid-cell.jstree-grid-cell-regular{
  display:  table-row;
}
div.jstree-grid-column{
  display:table-cell;
}
div.jstree-grid-wrapper{
  display:table;
}
```

**Comment by peternoges** [comment]
@deitch  I had no luck.  I think the solution can follow this approach: "Getting your DIVs to behave like TABLEs" https://snook.ca/archives/html_and_css/getting_your_di/  

Whereby using CSS we do the following:

> To make DIVs behave like TABLEs, you have to tell them to behave that way using the display property. The three key values that we'll be using are table, table-row and table-cell.
#container {
    display: table;
    }

  #row  {
    display: table-row;
    }

  #left, #right, #middle {
    display: table-cell;
    }


I don't know how to apply the same to jstreegrid since I don't know how to select all divs that comprise a "row", but here is a start:

div.jstree-grid-wrapper{
  display:table;
}

??

??

**Comment by deitch** [comment]
What happens when you do? Does it mess everything else up?

I distinctly remember the pain of moving this from actual table to div to solve one set of problems. If you can get it to work with the CSS without breaking anything, would be happy to see it and merge it in.

I don't really know how each OS "copies" into the clipboard (does it copy actual HTML+CSS? It's own format of representation?) and how each app handles the pasting of that unique format.

**Comment by peternoges** [comment]
I am working on a solution, for seamless copy/pasting jstreegrid column/row selections to excel and google sheets.  Currently exploring this example because it converts div-based tables to csv, which seems applicable to jstreegrid because jstreegrid uses the div-based table approach : http://www.marcorpsa.com/ee/t3091.html#

**Comment by peternoges** [comment]
@deitch what set of problems were solved by using divs rather than table elements? Thanks in advance for the information as I work through this

**Comment by deitch** [comment]
> what set of problems were solved by using divs rather than table elements? Thanks in advance for the information as I work through this

I don't recall everything at the moment - more than a few years ago, although you are welcome to sift through the older issues and code commits, if you have a masochistic streak - but there was a lot around widths and heights, resizing, etc.

If we could make this part of the jstree itself, it would solve some of the issues. But even jstree, being a tree, uses nested `ul` and `li` elements, which makes fitting it into a grid difficult.

In any case, do you know what it takes to make a table copyable from html and passable to Excel? Does a `table` with `tr` work where `div`s do not?
