### ISSUE TITLE
Creating root node issue 

### ISSUE THREAD

**Issue by rekhaNagi** [deitch/jstree-grid#81]
Hi i was using jstree 3.0.0 and now i updated to 3.0.8 and i have a functionality to create root node . But after updating to 3.0.8 root node is not created . I am using tree grid with jstree version 3.0.8 and jstreegrid 3.1.0

http://jsfiddle.net/7ympd539/6/

please go through this fiddle above

**Comment by bbredewold** [comment]
Have this problem, but even when loading nodes via json...

**Comment by deitch** [comment]
@bbredewold can you put up a fiddle? Use the following as a basis: http://jsfiddle.net/7ympd539/14/

**Comment by deitch** [comment]
FYI, I did figure out the problem, at least for the first issue. When we reparent the original tree `div` into the grid, we copy any classes from the original `div` to the new wrapper, so that any styling is caught. But in doing so, we also copy `jstree` and `jstree-` classes, which mess up the styling.

We can fix that!

**Comment by deitch** [comment]
Done. And `npm publish`ed
